### ISSUE TITLE
New Keycloak versions available

### ISSUE THREAD

**Issue by cromra** [Doccrazy/keycloak-protocol-cas#9]
There has been several versions, the last one is 4.4.0
Can we still use the keycloak-protocol-cas 4.1.0 for this last release as we are still on the same major version, or do we need new releases each time ?

**Comment by Doccrazy** [comment]
I pushed versions 4.2.0 (no changes) and 4.3.0 (backwards-incompatible). 4.3.0 should also work for Keycloak 4.4.0.Final if you need to upgrade, but I can't push that version just yet because the docker image required for Travis has not been released yet (https://hub.docker.com/r/jboss/keycloak/tags/).

I also added a semi-automatic update checker script for Travis that should (hopefully) PR new Keycloak versions.
